### ISSUE TITLE
NPM Install Failing

### ISSUE THREAD

**Issue by tianhuil** [nozzle/react-static#1031]
### Reporting a bug?

I am unable to install using `npm` but can install using `yarn`.  That is,
`npm install -g react-static` fails and I get a `npm ERR! Unexpected end of JSON input while parsing near '...aPefIHErkE61pl\noUbz6'`.  Full error below.

Note that `npm install -g react` and `yarn global add react-static` succeed.

### Environment

I'm on OSX.
```
~$ node -v
v10.9.0
~$ npm -v
6.8.0
~$ yarn -v
1.13.0
```

### Extended Logs

```
1 verbose cli   'react-static' ]
2 info using npm@6.8.0
3 info using node@v10.9.0
4 verbose npm-session cfe8827072ed9908
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react-static 180ms (from cache)
8 silly pacote tag manifest for react-static@latest fetched in 247ms
9 timing stage:loadCurrentTree Completed in 268ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule react-static@6.3.6 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-export-default-from 56ms (from cache)
18 silly pacote range manifest for @babel/plugin-proposal-export-default-from@^7.0.0 fetched in 59ms
19 silly resolveWithNewModule @babel/plugin-proposal-export-default-from@7.2.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-class-properties 129ms (from cache)
21 silly pacote range manifest for @babel/plugin-proposal-class-properties@^7.0.0 fetched in 139ms
22 silly resolveWithNewModule @babel/plugin-proposal-class-properties@7.3.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-syntax-dynamic-import 140ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-stage-0 85ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-transform-runtime 143ms (from cache)
26 silly pacote range manifest for @babel/plugin-syntax-dynamic-import@^7.0.0 fetched in 147ms
27 silly resolveWithNewModule @babel/plugin-syntax-dynamic-import@7.2.0 checking installable status
28 silly pacote range manifest for @babel/preset-stage-0@^7.0.0 fetched in 93ms
29 silly resolveWithNewModule @babel/preset-stage-0@7.0.0 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-react 148ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/@babel%2fcli 159ms (from cache)
32 silly pacote range manifest for @babel/plugin-transform-runtime@^7.0.0 fetched in 152ms
33 silly resolveWithNewModule @babel/plugin-transform-runtime@7.2.0 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 159ms (from cache)
35 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-optional-chaining 157ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-transform-destructuring 157ms (from cache)
37 silly pacote range manifest for @babel/preset-react@^7.0.0 fetched in 157ms
38 silly resolveWithNewModule @babel/preset-react@7.0.0 checking installable status
39 silly pacote range manifest for @babel/cli@^7.1.5 fetched in 169ms
40 silly resolveWithNewModule @babel/cli@7.2.3 checking installable status
41 silly pacote range manifest for @babel/core@^7.2.2 fetched in 170ms
42 silly resolveWithNewModule @babel/core@7.3.3 checking installable status
43 silly pacote range manifest for @babel/plugin-proposal-optional-chaining@^7.0.0 fetched in 168ms
44 silly resolveWithNewModule @babel/plugin-proposal-optional-chaining@7.2.0 checking installable status
45 silly pacote range manifest for @babel/plugin-transform-destructuring@^7.1.3 fetched in 170ms
46 silly resolveWithNewModule @babel/plugin-transform-destructuring@7.3.2 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 171ms (from cache)
48 silly pacote range manifest for @babel/preset-env@^7.1.5 fetched in 187ms
49 silly resolveWithNewModule @babel/preset-env@7.3.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/@babel%2fregister 97ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 96ms (from cache)
52 silly pacote range manifest for @babel/register@^7.0.0 fetched in 112ms
53 silly resolveWithNewModule @babel/register@7.0.0 checking installable status
54 http fetch GET 304 https://registry.npmjs.org/babel-plugin-macros 81ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/axios 94ms (from cache)
56 silly pacote range manifest for @babel/runtime@^7.1.5 fetched in 111ms
57 silly resolveWithNewModule @babel/runtime@7.3.1 checking installable status
58 silly pacote range manifest for babel-plugin-macros@^2.4.3 fetched in 91ms
59 silly resolveWithNewModule babel-plugin-macros@2.5.0 checking installable status
60 silly pacote range manifest for axios@^0.18.0 fetched in 107ms
61 silly resolveWithNewModule axios@0.18.0 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/autoprefixer 116ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/babel-loader 113ms (from cache)
64 silly pacote range manifest for autoprefixer@^9.4.3 fetched in 123ms
65 silly resolveWithNewModule autoprefixer@9.4.7 checking installable status
66 silly pacote range manifest for babel-loader@^8.0.0 fetched in 127ms
67 silly resolveWithNewModule babel-loader@8.0.5 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-react-remove-prop-types 110ms (from cache)
69 silly pacote range manifest for babel-plugin-transform-react-remove-prop-types@^0.4.20 fetched in 122ms
70 silly resolveWithNewModule babel-plugin-transform-react-remove-prop-types@0.4.24 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/babel-core 149ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin 69ms (from cache)
73 silly pacote version manifest for babel-core@7.0.0-bridge.0 fetched in 160ms
74 silly resolveWithNewModule babel-core@7.0.0-bridge.0 checking installable status
75 silly pacote range manifest for case-sensitive-paths-webpack-plugin@^2.1.2 fetched in 80ms
76 silly resolveWithNewModule case-sensitive-paths-webpack-plugin@2.2.0 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/babel-plugin-universal-import 92ms (from cache)
78 silly pacote range manifest for babel-plugin-universal-import@^3.0.2 fetched in 101ms
79 silly resolveWithNewModule babel-plugin-universal-import@3.1.2 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/chalk 105ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/circular-dependency-plugin 86ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/cors 79ms (from cache)
83 silly pacote range manifest for chalk@^2.4.1 fetched in 114ms
84 silly resolveWithNewModule chalk@2.4.2 checking installable status
85 silly pacote range manifest for circular-dependency-plugin@^5.0.2 fetched in 94ms
86 silly resolveWithNewModule circular-dependency-plugin@5.0.2 checking installable status
87 silly pacote range manifest for cors@^2.8.5 fetched in 86ms
88 silly resolveWithNewModule cors@2.8.5 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/css-loader 87ms (from cache)
90 http fetch GET 304 https://registry.npmjs.org/chokidar 134ms (from cache)
91 silly pacote range manifest for css-loader@^2.0.1 fetched in 93ms
92 silly resolveWithNewModule css-loader@2.1.0 checking installable status
93 http fetch GET 304 https://registry.npmjs.org/download-git-repo 76ms (from cache)
94 http fetch GET 304 https://registry.npmjs.org/eslint-config-react-tools 69ms (from cache)
95 silly fetchPackageMetaData error for eslint-config-react-tools@^1.0.0 Unexpected end of JSON input while parsing near '...rectories":{},"dist":'
96 silly pacote range manifest for chokidar@^2.0.4 fetched in 142ms
97 silly resolveWithNewModule chokidar@2.1.1 checking installable status
98 silly pacote range manifest for download-git-repo@^1.1.0 fetched in 84ms
99 silly resolveWithNewModule download-git-repo@1.1.0 checking installable status
100 http fetch GET 304 https://registry.npmjs.org/extract-css-chunks-webpack-plugin 78ms (from cache)
101 silly pacote range manifest for extract-css-chunks-webpack-plugin@^3.2.1 fetched in 90ms
102 silly resolveWithNewModule extract-css-chunks-webpack-plugin@3.3.2 checking installable status
103 http fetch GET 304 https://registry.npmjs.org/git-promise 64ms (from cache)
104 silly pacote range manifest for git-promise@^0.3.1 fetched in 68ms
105 silly resolveWithNewModule git-promise@0.3.1 checking installable status
106 http fetch GET 304 https://registry.npmjs.org/file-loader 75ms (from cache)
107 silly pacote version manifest for file-loader@2.0.0 fetched in 86ms
108 silly resolveWithNewModule file-loader@2.0.0 checking installable status
109 http fetch GET 304 https://registry.npmjs.org/gunzip-maybe 58ms (from cache)
110 silly pacote range manifest for gunzip-maybe@^1.4.1 fetched in 61ms
111 silly resolveWithNewModule gunzip-maybe@1.4.1 checking installable status
112 http fetch GET 304 https://registry.npmjs.org/fs-extra 93ms (from cache)
113 silly pacote range manifest for fs-extra@^7.0.1 fetched in 98ms
114 silly resolveWithNewModule fs-extra@7.0.1 checking installable status
115 http fetch GET 304 https://registry.npmjs.org/inquirer 91ms (from cache)
116 http fetch GET 304 https://registry.npmjs.org/html-webpack-plugin 97ms (from cache)
117 silly pacote range manifest for inquirer@^6.1.0 fetched in 98ms
118 silly resolveWithNewModule inquirer@6.2.2 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/inquirer-autocomplete-prompt 73ms (from cache)
120 silly pacote range manifest for html-webpack-plugin@^3.2.0 fetched in 106ms
121 silly resolveWithNewModule html-webpack-plugin@3.2.0 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/intersection-observer 65ms (from cache)
123 silly pacote range manifest for inquirer-autocomplete-prompt@^1.0.1 fetched in 79ms
124 silly resolveWithNewModule inquirer-autocomplete-prompt@1.0.1 checking installable status
125 silly pacote range manifest for intersection-observer@^0.5.1 fetched in 70ms
126 silly resolveWithNewModule intersection-observer@0.5.1 checking installable status
127 http fetch GET 304 https://registry.npmjs.org/@hot-loader%2freact-dom 377ms (from cache)
128 http fetch GET 304 https://registry.npmjs.org/glob 122ms (from cache)
129 silly fetchPackageMetaData error for @hot-loader/react-dom@^16.7.0-alpha.2.3 Unexpected end of JSON input while parsing near '...aPefIHErkE61pl\noUbz6'
130 silly pacote range manifest for glob@^7.1.2 fetched in 127ms
131 silly resolveWithNewModule glob@7.1.3 checking installable status
132 http fetch GET 304 https://registry.npmjs.org/match-sorter 75ms (from cache)
133 http fetch GET 304 https://registry.npmjs.org/mutation-observer 67ms (from cache)
134 silly pacote range manifest for match-sorter@^2.2.3 fetched in 82ms
135 silly resolveWithNewModule match-sorter@2.3.0 checking installable status
136 silly tarball trying https://registry.npmjs.org/match-sorter/-/match-sorter-2.3.0.tgz by hash: sha512-0/F1ezfjs5vegTvdH0sJEDrIi+w7wvUeDW/yqLMsK6jQWgNNJRv8jYCLBc8QrCxQNpSEpei6vrOcnJwAbnYhkw==
137 silly pacote range manifest for mutation-observer@^1.0.3 fetched in 75ms
138 silly resolveWithNewModule mutation-observer@1.0.3 checking installable status
139 http fetch GET 304 https://registry.npmjs.org/minimist 229ms (from cache)
140 http fetch GET 304 https://registry.npmjs.org/optimize-css-assets-webpack-plugin 194ms (from cache)
141 silly pacote range manifest for minimist@^1.2.0 fetched in 238ms
142 silly resolveWithNewModule minimist@1.2.0 checking installable status
143 silly pacote range manifest for optimize-css-assets-webpack-plugin@^5.0.0 fetched in 201ms
144 silly resolveWithNewModule optimize-css-assets-webpack-plugin@5.0.1 checking installable status
145 http fetch GET 304 https://registry.npmjs.org/postcss-flexbugs-fixes 192ms (from cache)
146 http fetch GET 304 https://registry.npmjs.org/progress 183ms (from cache)
147 silly pacote range manifest for postcss-flexbugs-fixes@^4.1.0 fetched in 200ms
148 silly resolveWithNewModule postcss-flexbugs-fixes@4.1.0 checking installable status
149 http fetch GET 304 https://registry.npmjs.org/@reach%2frouter 617ms (from cache)
150 silly pacote range manifest for progress@^2.0.1 fetched in 239ms
151 silly resolveWithNewModule progress@2.0.3 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/pretty-error 247ms (from cache)
153 http fetch GET 304 https://registry.npmjs.org/portfinder 260ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/raf 224ms (from cache)
155 http fetch GET 304 https://registry.npmjs.org/postcss-loader 259ms (from cache)
156 silly pacote range manifest for @reach/router@^1.2.1 fetched in 630ms
157 silly resolveWithNewModule @reach/router@1.2.1 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/prop-types 234ms (from cache)
159 silly pacote range manifest for pretty-error@^2.1.1 fetched in 258ms
160 silly resolveWithNewModule pretty-error@2.1.1 checking installable status
161 silly pacote range manifest for portfinder@^1.0.20 fetched in 270ms
162 silly resolveWithNewModule portfinder@1.0.20 checking installable status
163 silly pacote range manifest for raf@^3.4.1 fetched in 233ms
164 silly resolveWithNewModule raf@3.4.1 checking installable status
165 silly pacote range manifest for postcss-loader@^3.0.0 fetched in 268ms
166 silly resolveWithNewModule postcss-loader@3.0.0 checking installable status
167 silly pacote range manifest for prop-types@^15.6.1 fetched in 246ms
168 silly resolveWithNewModule prop-types@15.7.2 checking installable status
169 http fetch GET 304 https://registry.npmjs.org/raw-loader 104ms (from cache)
170 silly pacote range manifest for raw-loader@^1.0.0 fetched in 108ms
171 silly resolveWithNewModule raw-loader@1.0.0 checking installable status
172 http fetch GET 304 https://registry.npmjs.org/react 142ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/react-helmet 75ms (from cache)
174 silly pacote range manifest for react@^16.8.1 fetched in 149ms
175 silly resolveWithNewModule react@16.8.2 checking installable status
176 silly pacote range manifest for react-helmet@^5.2.0 fetched in 80ms
177 silly resolveWithNewModule react-helmet@5.2.0 checking installable status
178 http fetch GET 304 https://registry.npmjs.org/react-dev-utils 145ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/shorthash 72ms (from cache)
180 silly pacote range manifest for react-dev-utils@^6.1.1 fetched in 151ms
181 silly resolveWithNewModule react-dev-utils@6.1.1 checking installable status
182 silly pacote range manifest for shorthash@^0.0.2 fetched in 78ms
183 silly resolveWithNewModule shorthash@0.0.2 checking installable status
184 http fetch GET 304 https://registry.npmjs.org/resolve-from 89ms (from cache)
185 http fetch GET 304 https://registry.npmjs.org/react-universal-component 94ms (from cache)
186 http fetch GET 304 https://registry.npmjs.org/react-dom 111ms (from cache)
187 silly pacote range manifest for resolve-from@^4.0.0 fetched in 97ms
188 silly resolveWithNewModule resolve-from@4.0.0 checking installable status
189 http fetch GET 304 https://registry.npmjs.org/serve 96ms (from cache)
190 http fetch GET 304 https://registry.npmjs.org/react-hot-loader 109ms (from cache)
191 silly pacote range manifest for react-universal-component@^3.0.2 fetched in 112ms
192 silly resolveWithNewModule react-universal-component@3.0.3 checking installable status
193 silly pacote range manifest for react-dom@^16.8.1 fetched in 129ms
194 silly resolveWithNewModule react-dom@16.8.2 checking installable status
195 silly pacote range manifest for serve@^10.1.1 fetched in 110ms
196 silly resolveWithNewModule serve@10.1.2 checking installable status
197 silly pacote range manifest for react-hot-loader@^4.6.1 fetched in 121ms
198 silly resolveWithNewModule react-hot-loader@4.6.5 checking installable status
199 http fetch GET 304 https://registry.npmjs.org/slash 105ms (from cache)
200 silly pacote range manifest for slash@^2.0.0 fetched in 112ms
201 silly resolveWithNewModule slash@2.0.0 checking installable status
202 http fetch GET 304 https://registry.npmjs.org/socket.io 96ms (from cache)
203 http fetch GET 304 https://registry.npmjs.org/tar-fs 75ms (from cache)
204 http fetch GET 304 https://registry.npmjs.org/style-loader 89ms (from cache)
205 silly pacote range manifest for socket.io@^2.1.1 fetched in 105ms
206 silly resolveWithNewModule socket.io@2.2.0 checking installable status
207 silly pacote range manifest for tar-fs@^1.16.3 fetched in 84ms
208 silly resolveWithNewModule tar-fs@1.16.3 checking installable status
209 silly pacote version manifest for style-loader@0.23.1 fetched in 98ms
210 silly resolveWithNewModule style-loader@0.23.1 checking installable status
211 http fetch GET 304 https://registry.npmjs.org/swimmer 99ms (from cache)
212 http fetch GET 304 https://registry.npmjs.org/socket.io-client 110ms (from cache)
213 http fetch GET 304 https://registry.npmjs.org/thread-loader 73ms (from cache)
214 silly pacote range manifest for swimmer@^1.4.0 fetched in 106ms
215 silly resolveWithNewModule swimmer@1.4.0 checking installable status
216 http fetch GET 304 https://registry.npmjs.org/terser-webpack-plugin 82ms (from cache)
217 silly pacote range manifest for socket.io-client@^2.1.1 fetched in 123ms
218 silly resolveWithNewModule socket.io-client@2.2.0 checking installable status
219 silly pacote range manifest for thread-loader@^1.2.0 fetched in 89ms
220 silly resolveWithNewModule thread-loader@1.2.0 checking installable status
221 silly pacote range manifest for terser-webpack-plugin@^1.2.2 fetched in 96ms
222 silly resolveWithNewModule terser-webpack-plugin@1.2.2 checking installable status
223 http fetch GET 304 https://registry.npmjs.org/upath 96ms (from cache)
224 silly pacote range manifest for upath@^1.1.0 fetched in 99ms
225 silly resolveWithNewModule upath@1.1.0 checking installable status
226 http fetch GET 304 https://registry.npmjs.org/url-loader 97ms (from cache)
227 silly pacote range manifest for url-loader@^1.1.2 fetched in 99ms
228 silly resolveWithNewModule url-loader@1.1.2 checking installable status
229 http fetch GET 304 https://registry.npmjs.org/webpack-flush-chunks 50ms (from cache)
230 silly pacote range manifest for webpack-flush-chunks@^2.0.1 fetched in 56ms
231 silly resolveWithNewModule webpack-flush-chunks@2.0.3 checking installable status
232 http fetch GET 304 https://registry.npmjs.org/webpack-bundle-analyzer 63ms (from cache)
233 silly pacote range manifest for webpack-bundle-analyzer@^3.0.3 fetched in 66ms
234 silly resolveWithNewModule webpack-bundle-analyzer@3.0.4 checking installable status
235 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 69ms (from cache)
236 silly pacote range manifest for webpack-dev-server@^3.1.10 fetched in 74ms
237 silly resolveWithNewModule webpack-dev-server@3.1.14 checking installable status
238 http fetch GET 304 https://registry.npmjs.org/webpack-node-externals 80ms (from cache)
239 silly pacote range manifest for webpack-node-externals@^1.7.2 fetched in 82ms
240 silly resolveWithNewModule webpack-node-externals@1.7.2 checking installable status
241 silly extract https://registry.npmjs.org/match-sorter/-/match-sorter-2.3.0.tgz extracted to /var/folders/2c/spm2_5bx6jj7mpd3rl9nvk8m0000gn/T/npm-92092-7644b283/unpack-b04fd587 (546ms)
242 silly addBundled read tarball
243 silly cleanup remove extracted module
244 http fetch GET 200 https://registry.npmjs.org/webpack 1341ms
245 silly pacote range manifest for webpack@^4.25.1 fetched in 1358ms
246 silly resolveWithNewModule webpack@4.29.5 checking installable status
247 timing stage:rollbackFailedOptional Completed in 0ms
248 timing stage:runTopLevelLifecycles Completed in 2611ms
249 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...rectories":{},"dist":'
249 verbose stack     at JSON.parse (<anonymous>)
249 verbose stack     at parseJson (~/.npm-packages/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
249 verbose stack     at consumeBody.call.then.buffer (~/.npm-packages/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
249 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
250 verbose cwd ~
251 verbose Darwin 18.2.0
252 verbose argv "/usr/local/bin/node" "~/.npm-packages/bin/npm" "install" "-g" "react-static"
253 verbose node v10.9.0
254 verbose npm  v6.8.0
255 error Unexpected end of JSON input while parsing near '...rectories":{},"dist":'
256 verbose exit [ 1, true ]

**Comment by sw-yx** [comment]
we're experiencing this across the board, npm suddenly doesnt work for us but yarn is. not sure what caused it.

**Comment by sw-yx** [comment]
hey OP - we cannot replicate - can you or anyone else seeing this try to repro please https://twitter.com/ReBeccaOrg/status/1097559461906939904

**Comment by jchip** [comment]
I installed with npm 6.8.0 and save the node_modules, and run the command:

```bash
find . -name package.json | xargs grep ^\ \ \"version\" > ../6.3.6.npm.txt
```

and 

```bash
find . -name package.json | xargs grep ^\ \ \"version\" > ../6.3.2.npm.txt
```

And then `diff 6.3.2.npm.txt 6.3.6.npm.txt`, looks like `uglifyjs-webpack-plugin` is the only change:

```
[thalion-herohtar]$ !diff
diff 6.3.2.npm.txt 6.3.6.npm.txt
839c839
< ./react-static/package.json:  "version": "6.3.2"
---
> ./react-static/package.json:  "version": "6.3.6"
1122,1130d1121
< ./uglifyjs-webpack-plugin/node_modules/pkg-dir/package.json:  "version": "3.0.0"
< ./uglifyjs-webpack-plugin/node_modules/p-locate/package.json:  "version": "3.0.0"
< ./uglifyjs-webpack-plugin/node_modules/p-limit/package.json:  "version": "2.1.0"
< ./uglifyjs-webpack-plugin/node_modules/find-up/package.json:  "version": "3.0.0"
< ./uglifyjs-webpack-plugin/node_modules/find-cache-dir/package.json:  "version": "2.0.0"
< ./uglifyjs-webpack-plugin/node_modules/source-map/package.json:  "version": "0.6.1"
< ./uglifyjs-webpack-plugin/node_modules/p-try/package.json:  "version": "2.0.0"
< ./uglifyjs-webpack-plugin/node_modules/locate-path/package.json:  "version": "3.0.0"
< ./uglifyjs-webpack-plugin/package.json:  "version": "2.1.1"
```

**Comment by tannerlinsley** [comment]
This is likely a bug related to #1027 and an upstream npm issue. Going to track it there.

**Comment by tianhuil** [comment]
Thanks for tracking @tannerlinsley!
