### ISSUE TITLE
[QUESTION]: Support for Flow types in static.config.js

### ISSUE THREAD

**Issue by rodilo** [nozzle/react-static#1257]
After upgrading from v6 to v7, this issue occurred. If `static.config.js` file has imports with Flow types, app start and build doesn't work, I get this error:

```
$ react-static start
Starting Development Server...
  Error: [object Object]
      at init.catch.e (/*/node_modules/react-static/bin/react-static:6:11)
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:122:5)
      at _combinedTickCallback (internal/process/next_tick.js:132:7)
      at process._tickCallback (internal/process/next_tick.js:181:9)
      at Function.Module.runMain (module.js:696:11)
      at startup (bootstrap_node.js:204:16)
      at bootstrap_node.js:625:3

error Command failed with exit code 1.
```
This is how my .babelrc looks like:

```
{
  "extends": "./node_modules/react-static/.babelrc",
  "presets": ["@babel/preset-flow"]
}
```
If i remove Flow types, everything works fine, but that is not solution for me since i have multiple files that are imported into static.config.js (i use those for creating routes, fetching some route data etc).

Again, this is working fine in V6.

I've tried editing `/node_modules/react-static/babel-preset.js` file where I added `@babel/preset-flow` preset and that fixed it. 
```
...
 if (node) {
    return {
      presets: [
        r('@babel/preset-env'),
        **r('@"@babel/preset-flow')**
        [r('@babel/preset-react'), { development: false }],
      ],
      plugins: [
        r('babel-plugin-macros'),
        r('@babel/plugin-syntax-dynamic-import'),
        r('@babel/plugin-transform-destructuring'),
        r('@babel/plugin-transform-runtime'),
        r('@babel/plugin-proposal-class-properties'),
        r('@babel/plugin-proposal-optional-chaining'),
        r('@babel/plugin-proposal-export-default-from'),
      ],
    }
  }
...
```
My question is is it possible to override babel-preset.js somehow? Or is it possible to add some babel preset in it, through some api? 

Any help is appreciated.

**Comment by sw-yx** [comment]
hi everyone! thanks for your PR! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by SleeplessByte** [comment]
It seems that the preset fails for the `react-static` source files, but not your own. Have you tried adding a `.babelrc` in the `src` folder, and have it exclude `node_modules`? You only want to run the preset on your source code.

**Comment by rodilo** [comment]
@SleeplessByte 

I've added `.babelrc`  in the `src`, but still same issue. This is the content of that file:

```
{
  "extends": "./node_modules/react-static/.babelrc",
  "presets": ["@babel/preset-flow"],
  "ignore": ["node_modules"]
}
```

**Comment by SleeplessByte** [comment]
Got it. I'll see if we can generate some real working examples!
