### ISSUE TITLE
Problems getting started: unhandled error in events.js:182

### ISSUE THREAD

**Issue by joshpitzalis** [nozzle/react-static#13]
I did the following in my terminal...

1. yarn global add react-static
2. react-static create <myProjectName>
3. cd <myProjectName>
4. yarn start

and I got...

```=> Copying public directory...
=> [✓] Public directory copied: 8.029ms
=> Building...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at Server.listen (net.js:1474:7)
    at Server.listen (/Users/josh/.config/yarn/global/node_modules/webpack-dev-server/lib/Server.js:556:41)
    at startDevServer (/Users/josh/.config/yarn/global/node_modules/react-static/dist/commands/start.js:279:13)
    at _callee4$ (/Users/josh/.config/yarn/global/node_modules/react-static/dist/commands/start.js:356:13)
    at tryCatch (/Users/josh/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/josh/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:299:22)```

Did I do something wrong or is this a bug?

I'm on OSX 10.12.5, node v8.5.0, "react-static": "^1.0.43"

**Comment by joshpitzalis** [comment]
I had something else running in a separate terminal window. My bad.
