### ISSUE TITLE
Error in build if 404 route not provided

### ISSUE THREAD

**Issue by mplis** [nozzle/react-static#138]
If an `is404` route is not in the routes array returned from `getRoutes`, running the build command results in this error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: boolean.
    in Route
    in Routes
    in div
    in div
    in Router
    in StaticRouter
    in Router
    in _default
    in InitialPropsContext
    in ContextualComp
TypeError: element.type.toLowerCase is not a function
    at ReactDOMServerRenderer.renderDOM (/Users/mplis/personal/misc/my-static-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:2776:28)
    at ReactDOMServerRenderer.render (/Users/mplis/personal/misc/my-static-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:2755:23)
    at ReactDOMServerRenderer.read (/Users/mplis/personal/misc/my-static-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:2722:19)
    at renderToString (/Users/mplis/personal/misc/my-static-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:2980:25)
    at Object.renderToHtml (/Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/utils.js:107:14)
    at _callee$ (/Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:236:39)
    at tryCatch (/Users/mplis/personal/misc/my-static-site/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/mplis/personal/misc/my-static-site/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mplis/personal/misc/my-static-site/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:120:191)
    at /Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:120:437
    at Promise (<anonymous>)
    at /Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:120:99
    at /Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:356:30
    at Array.map (<anonymous>)
    at _callee2$ (/Users/mplis/personal/misc/my-static-site/node_modules/react-static/lib/static.js:148:73)
```

I believe the problem is in the generated `react-static-routes.js` file, specifically the [`getTemplateForPath`](https://github.com/nozzle/react-static/blob/828038865859640da10136b451eb846076f7fd30/src/static.js#L263) function. That function is called inside the [`mainRouteComp`](https://github.com/nozzle/react-static/blob/828038865859640da10136b451eb846076f7fd30/src/static.js#L282) and it returns `false` when called with a value of `'404'`. The following error is being thrown in that case and being swallowed [here](https://github.com/nozzle/react-static/blob/828038865859640da10136b451eb846076f7fd30/src/static.js#L273):
```
TypeError: Cannot read property 't' of undefined
    at getTemplateForPath (/Users/mplis/personal/misc/my-static-site/dist/app.static.7bbc1e0c.js:286:24)
    at render (/Users/mplis/personal/misc/my-static-site/dist/app.static.7bbc1e0c.js:305:26)
    at Route.render (/Users/mplis/personal/misc/my-static-site/node_modules/react-router/Route.js:124:13)
    at resolve (/Users/mplis/personal/misc/my-static-site/node_modules/react-dom/cjs/react-dom-server.node.development.js:2646:18)
...
```

Ultimately, I believe that the template tree is not being correctly built [here](https://github.com/nozzle/react-static/blob/828038865859640da10136b451eb846076f7fd30/src/static.js#L240). This is the output if I log `tree` at [this](https://github.com/nozzle/react-static/blob/828038865859640da10136b451eb846076f7fd30/src/static.js#L258) point:

```
tree { c: { '/': { t: 't_0' } } }
```

I believe the expectation is that there's a '404' key in there, but there's not. I'm not familiar enough with the codebase to know exactly where the change needs to be made to fix this, whether it's in this file or somewhere farther upstream in the build process.

**Comment by mplis** [comment]
I think the problem is the combination of [this](https://github.com/nozzle/react-static/blob/f62e38dfd178063d36282d15cc58c3e388e498c7/src/utils.js#L132) bit of code and [this](https://github.com/nozzle/react-static/blob/74de3ae7e229edb51793a3d064ffa73acee3800b/src/static.js#L222) line.

The former adds a default 404 route if one isn't provided, but the latter filters it out (since there's no `component`) when creating the `templateTree`.

**Comment by tannerlinsley** [comment]
Fixed in latest release
