### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by mplis** [nozzle/react-static#25]
I'm seeing this stack trace (only in development mode) when trying to generate a site with a lot of routes (~6000)

```
RangeError: Invalid string length
    at Object.stringify (native)
    at stringify (/Users/mike/workspace/react-static-test/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/Users/mike/workspace/react-static-test/node_modules/express/lib/response.js:260:14)
    at _callee3$ (/Users/mike/workspace/react-static-test/node_modules/react-static/dist/commands/start.js:133:29)
    at tryCatch (/Users/mike/workspace/react-static-test/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mike/workspace/react-static-test/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mike/workspace/react-static-test/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/mike/workspace/react-static-test/node_modules/react-static/dist/commands/start.js:238:191)
    at /Users/mike/workspace/react-static-test/node_modules/react-static/dist/commands/start.js:238:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

This is occurring on the call to the `getroutes` endpoint. If I reduce the number of routes down to around 1000, you can see that the response from `getroutes` is fairly large (15.6 MB)

<img width="604" alt="screen shot 2017-10-11 at 6 53 05 am" src="https://user-images.githubusercontent.com/1382377/31437001-c7e9bdca-ae51-11e7-8b7a-454cd0b86926.png">

It looks like this is happening because each route in the returned object includes it's `parent` which includes all of it's `children` so the size of the response grows very quickly if a route has a lot of children. Somewhere in the code is probably calling `JSON.stringify` on this object and it's so large that it's throwing the error.

<img width="240" alt="screen shot 2017-10-11 at 6 53 59 am" src="https://user-images.githubusercontent.com/1382377/31437084-0dfa4d16-ae52-11e7-943c-eb85f91344e4.png">

Would it be possible to remove the `children` field from `parent`?

**Comment by tannerlinsley** [comment]
Yes, I'll just flatten the list.
