### ISSUE TITLE
TypeError: Object.values is not a function during Exporting Routes on build

### ISSUE THREAD

**Issue by cliffasaurus** [nozzle/react-static#251]
I'm building from the sass template with my config file:
```
import ExtractTextPlugin from 'extract-text-webpack-plugin'

export default {
  getRoutes: async () => {
    return [
      {
        path: '/',
        component: 'src/containers/Home',
      },
//+ other routes

```

and App,js has the basic example for routing:

```
import React from 'react'
import { Router } from 'react-static'
import Routes from 'react-static-routes'

import './app.scss'

export default () => (
  <Router>
    <Routes />
  </Router>
);
```

dev server from localhost works well but this error shows up on build:

```
=> [✓] App Bundled: 31475.245ms
=> Exporting Routes...
TypeError: Object.values is not a function
    at _callee$ (C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:177:32)
    at tryCatch (C:\Users\John\Documents\Projects\test-site\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\John\Documents\Projects\test-site\node_modules\regenerator-runtime
\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\John\Documents\Projects\test-site\node_module
s\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:120:437
    at C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:120:99
    at C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:205:30
    at Array.map (native)
    at _callee4$ (C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:149:46)
    at tryCatch (C:\Users\John\Documents\Projects\test-site\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\John\Documents\Projects\test-site\node_modules\regenerator-runtime
\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\John\Documents\Projects\test-site\node_module
s\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\John\Documents\Projects\test-site\node_modules\react-static\lib\static.js:120:361
```

**Comment by tannerlinsley** [comment]
First, check that you are ok the latest version. Next, please post a link
to your repo or at least paste your config and any other relevant files.
Then we can help you debug the problem 👍

**Comment by atfzl** [comment]
I also faced this problem. It was because I was using node 6 which does not support Object.values, see [Object.values node support](http://node.green/#ES2017-features-Object-static-methods-Object-values).
It is safe to use with node version >= 7.5.0

@tannerlinsley we should add `engines` key in package.json of react-static.

```
"engines" : { "node" : ">=7.5.0" }
```

**Comment by tannerlinsley** [comment]
Please PR that! :)

**Comment by tannerlinsley** [comment]
NM, I got it in the next release. 👍

**Comment by assisthiago** [comment]
https://stackoverflow.com/questions/6237295/how-can-i-update-nodejs-and-npm-to-the-next-versions
