### ISSUE TITLE
Error: socket hang up - build fails

### ISSUE THREAD

**Issue by imkevinjones** [nozzle/react-static#253]
After installing `react-static@4.7.1`, creating a project using `react-static create`, attempting to either build or run the dev server results in an error.

steps to reproduce:

1. `yarn global add react-static`
2. `react-static create`
3. enter project name `test`
4. select 'styled-components' template
5. after successful project creation without any errors, attempted running `yarn start` from project folder.

Also tried `yarn build`, and `react-static start`. Same output as below.

```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: 'localhost',
  port: '3128',
  localAddress: undefined,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.16.2',
        host: 'jsonplaceholder.typicode.com' },
     method: 'get',
     url: 'https://jsonplaceholder.typicode.com/posts',
     data: undefined },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { maxRedirects: 21,
        protocol: 'https:',
        hostname: 'localhost',
        port: '3128',
        path: 'https://jsonplaceholder.typicode.com/posts',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        host: 'localhost',
        pathname: 'https://jsonplaceholder.typicode.com/posts' },
     _redirectCount: 0,
     _bufferedWrites: [],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET https://jsonplaceholder.typicode.com/posts HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nhost: jsonplaceholder.typicode.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: 'https://jsonplaceholder.typicode.com/posts',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://localhost/https://jsonplaceholder.typicode.com/posts' },
  response: undefined }
error Command failed with exit code 1.
```

![image](https://user-images.githubusercontent.com/9055095/34235689-7eed063a-e647-11e7-89c8-8ae47c7c66df.png)

**Comment by tannerlinsley** [comment]
What version of node are you using?

**Comment by imkevinjones** [comment]
@tannerlinsley I've had success using node 9.3.0 from home, but not from behind my corporate proxy. Still no dice. What is it trying to hit during the build?

**Comment by imkevinjones** [comment]
Closing ticket as it is a non-issue. Thanks @tannerlinsley!

**Comment by tannerlinsley** [comment]
Awesome. 🙏!

**Comment by motevallian** [comment]
I have the exact same problem, I tried node versions 8.9.1 and 8.9.4.
I am using yarn as well.
I am behind a proxy but I can access the post via curl command without a problem (`https://jsonplaceholder.typicode.com/posts` is totally accessible).
I do not think it is OK that `react-static` fails behind a proxy.
Please advise me how to get it running behind the proxy.

**Comment by motevallian** [comment]
I noticed the problem I have is with `https`, when I changed it to `http` it worked fine:
`http://jsonplaceholder.typicode.com/posts` works for me.
