### ISSUE TITLE
Error `Object.values is not a function`, at production build 

### ISSUE THREAD

**Issue by trebushuk** [nozzle/react-static#266]
```
=> Exporting Routes...
TypeError: Object.values is not a function
    at _callee$ (/home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:178:32)
    at tryCatch (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:120:191)
    at /home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:120:437
    at /home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:120:99
    at /home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:206:30
    at Array.map (native)
    at _callee4$ (/home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:150:46)
    at tryCatch (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/vladimir/Workspace/site/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:120:191)
    at /home/vladimir/Workspace/site/node_modules/react-static/lib/static.js:120:361
error Command failed with exit code 1.
```
.babelrc
```
{
  "extends": "react-static/.babelrc",
  "plugins": ["transform-runtime"],
  "presets": ["es2017"]
}
```

**Comment by tannerlinsley** [comment]
Try upgrading your node version

**Comment by trebushuk** [comment]
Solved
