### ISSUE TITLE
Got error when generating production build via react-static create (basic example)

### ISSUE THREAD

**Issue by angelom88** [nozzle/react-static#270]
It works when just using development environment but when I want to generate production build. I encountered below stacktrace error.

pm ERR! node v6.11.5
npm ERR! npm  v3.10.10

I both use yarn and npm but encountered the same error.

```
MINGW64 ~/Development/my-projects/sd-ui/SD
$ yarn build
yarn run v1.3.2
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 2.908ms
=> Building Routes...
=> [✓] Routes Built: 328.922ms
=> Bundling App...
=> [✓] App Bundled: 5426.321ms
=> Exporting Routes...
TypeError: Object.values is not a function
    at _callee$ (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:178:32)
    at tryCatch (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:437
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:99
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:206:30
    at Array.map (native)
    at _callee4$ (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:150:46)
    at tryCatch (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:361
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

using npm run build:

```

MINGW64 ~/Development/my-projects/sd-ui/SD
$ npm run build

> react-static-example-basic@1.0.1 build C:\Users\angelo\Development\my-projects\sd-ui\SD
> react-static build


=> Copying public directory...
=> [✓] Public directory copied: 2.475ms
=> Building Routes...
=> [✓] Routes Built: 318.793ms
=> Bundling App...
=> [✓] App Bundled: 5303.054ms
=> Exporting Routes...
TypeError: Object.values is not a function
    at _callee$ (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:178:32)
    at tryCatch (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:437
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:99
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:206:30
    at Array.map (native)
    at _callee4$ (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:150:46)
    at tryCatch (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\angelo\Development\my-projects\sd-ui\SD\node_modules\react-static\lib\static.js:120:361

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\opt\\drives\\c\\nodejs\\node.exe" "C:\\opt\\drives\\c\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-static-example-basic@1.0.1 build: `react-static build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-static-example-basic@1.0.1 build script 'react-static build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-static-example-basic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-static build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-static-example-basic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-static-example-basic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\angelo\Development\my-projects\sd-ui\SD\npm-debug.log

```

**Comment by tannerlinsley** [comment]
Try upgrading your node version

**Comment by angelom88** [comment]
@tannerlinsley Yah it looks good now using node(v8.9.3). Anyway will be doing revamp using this [react-static library](https://github.com/nozzle/react-static) in my utility project [Slide Downloader](url) . Big thanks! :+1:
