### ISSUE TITLE
error when trying to build

### ISSUE THREAD

**Issue by knsakib** [nozzle/react-static#276]
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-static-example-basic@1.0.1~prebuild: react-static-example-basic@1.0.1
6 info lifecycle react-static-example-basic@1.0.1~build: react-static-example-basic@1.0.1
7 verbose lifecycle react-static-example-basic@1.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle react-static-example-basic@1.0.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/khalidsakib/Documents/devOps/myblog/knsakib-blog-creat-react-app/node_modules/.bin:/usr/local/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/opt/X11/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/usr/local/apache-maven/apache-maven-3.3.3/bin:/usr/local/mysql/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/esptools/esp-open-sdk/xtensa-lx106-elf/bin
9 verbose lifecycle react-static-example-basic@1.0.1~build: CWD: /Users/khalidsakib/Documents/devOps/myblog/knsakib-blog-creat-react-app
10 silly lifecycle react-static-example-basic@1.0.1~build: Args: [ '-c', 'react-static build' ]
11 silly lifecycle react-static-example-basic@1.0.1~build: Returned: code: 1  signal: null
12 info lifecycle react-static-example-basic@1.0.1~build: Failed to exec build script
13 verbose stack Error: react-static-example-basic@1.0.1 build: `react-static build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid react-static-example-basic@1.0.1
15 verbose cwd /Users/khalidsakib/Documents/devOps/myblog/knsakib-blog-creat-react-app
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v6.10.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error react-static-example-basic@1.0.1 build: `react-static build`
22 error Exit status 1
23 error Failed at the react-static-example-basic@1.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tannerlinsley** [comment]
This doesn't appear to be an error specific to react-static.  If it is, we'll need more information or a more detailed stack trace to determine if it is and what to do about it. Closing this for now, but if you do find more information, please post it and reopen the issue. 

I would recommend installing `react-static` globally and using `react-static create` to create a new project from scratch on your machine to verify that it works.
