### ISSUE TITLE
Errors when attempting to build [Could be my fault]

### ISSUE THREAD

**Issue by loganpowell** [nozzle/react-static#281]
Working with the `antd` example, which is working in development it seems, but when I tried to build it I got the following error:

```
=> Copying public directory...
=> [✓] Public directory copied: 107.163ms
=> Building Routes...
=> [✓] Routes Built: 154.821ms
=> Bundling App...
Version: webpack 3.10.0
Time: 105ms

ERROR in Entry module not found: Error: Can't resolve 'ts-loader' in 'C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\node_modules'

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!

Version: webpack 3.10.0
Time: 89ms

ERROR in Entry module not found: Error: Can't resolve 'ts-loader' in 'C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\node_modules'

                => There were ERRORS during the node build stage! :(
                => Fix them and try again!

=> [✓] App Bundled: 5128.856ms
=> Exporting Routes...
TypeError: Cannot read property 'split' of undefined
    at _callee4$ (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\static.js:138:30)
    at tryCatch (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\static.js:120:191)
    at C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\static.js:120:437
    at Promise (<anonymous>)
    at C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\static.js:120:99
    at exportRoutes (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\static.js:487:17)
    at _callee$ (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\commands\build.js:90:45)
    at tryCatch (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\commands\build.js:27:191)
    at C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\commands\build.js:27:361
    at <anonymous>

```

I hope I didn't do anything to break the setup. I don't use typescript, so I changed some of the files from `.tsx` to `.js` in my project files (e.g., `App.tsx`). What might I be doing wrong?

**Comment by loganpowell** [comment]
Hold on. Now it's not working in dev... let me try some things...

**Comment by loganpowell** [comment]
So, `yarn start` works, but `react-static start` does not (gives me the error above). Any pointers?

**Comment by tannerlinsley** [comment]
If react static cli isn't working make sure your global install of react
static is up to date

**Comment by loganpowell** [comment]
```
λ npm install -g react-static
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-latest@6.24.1: We're super �  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets � , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user � ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel �, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2016@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel-preset-es2017@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\react-static\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\surface\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-static"
npm ERR! node v8.1.4
npm ERR! npm  v4.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\surface\AppData\Roaming\npm-cache\_logs\2018-01-06T21_04_29_796Z-debug.log
```

What am I missing? :(

**Comment by loganpowell** [comment]
Looks like [this](https://github.com/npm/npm/issues/18979) might be the culprit:

https://github.com/npm/npm/issues/18979

**Comment by loganpowell** [comment]
Yep, I got an update at 9pm last night (i've been using `yarn start` the whole time, so didn't notice until I tried to `build`). This is a Windows issue, not React Static.

**Comment by loganpowell** [comment]
So, this is [F'ing crazy showing up on HN](https://news.ycombinator.com/item?id=16087024#16087126)... I think this what happened :D

```

seldo 8 minutes ago [-]Hi folks, npm COO here. This was an operational issue that we worked to correct. All packages are now restored:https://status.npmjs.org/incidents/41zfb8qpvrdjreply | seldo 8 minutes ago [-]Hi folks, npm COO here. This was an operational issue that we worked to correct. All packages are now restored:https://status.npmjs.org/incidents/41zfb8qpvrdjreply
-- | --
seldo 8 minutes ago [-]
Hi folks, npm COO here. This was an operational issue that we worked to correct. All packages are now restored:https://status.npmjs.org/incidents/41zfb8qpvrdjreply
xwvvvvwx
```
I got the biblical echo that's at the top of the thread as well.

**Comment by loganpowell** [comment]
If you want to see the most epic Github issue ever:

https://github.com/npm/registry/issues/255
