### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by mohammedzamakhan** [nozzle/react-static#29]
When I used `react-static create` to create the sample application and selected `basic` template, I get this error when I ran `yarn build`

```
ERROR in ./src/App.js
Module not found: Error: Can't resolve 'react-static-routes' in '/Users/Zama/Desktop/passion/my-static-site/src'
 @ ./src/App.js 13:25-55
 @ ./src/index.js
 @ multi ./src/index

=> There were ERRORS during the production build stage! :(
=> Fix them and try again!
```

and when I selected `custom routing`, I got this error

```
TypeError: (0 , _reactStatic.getSiteProps) is not a function
    at Object.<anonymous> (/Users/Zama/Desktop/passion/custom-static-site/src/containers/Home.js:4:16)
    at Module._compile (module.js:570:32)
    at loader (/Users/Zama/Desktop/passion/custom-static-site/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Zama/Desktop/passion/custom-static-site/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Zama/Desktop/passion/custom-static-site/src/App.js:4:1)
```

**Comment by whmountains** [comment]
I'm having the same problem.  Fresh application using the `styled-components` template on MacOS High Sierra.

**Comment by tannerlinsley** [comment]
I'll look into this ASAP

**Comment by tannerlinsley** [comment]
This should be fixed in the latest release. Be sure to upgrade your global react-static and local react-static for any existing projects

**Comment by CyberKronos** [comment]
@tannerlinsley Still having the same issue

**Comment by tannerlinsley** [comment]
What version of node and react static are you using? Did you update both
the global and internal dependency?

**Comment by CyberKronos** [comment]
Node: v8.3.0
react-static: 1.2.5

Yes I have updated everything. The react-static-routes isn't present in the node_modules.

**Comment by CyberKronos** [comment]
My mistake all is good now! Thanks for the response.

**Comment by neilyoung** [comment]
Hmm. No I'm having exactly this problem, after years. Was all the time developing on macOS with a react-static of 5.9.12.

Now out of the sudden on an Ubuntu 18.04 this happens at the very first build step of `npm run build`

```
decades@ubuntu:~/dfja/dragonfly2/spa$ npm run build

> dragonfly-java-dashboard@1.8.0 build /home/decades/dfja/dragonfly2/spa
> react-static build && sh ./cp.sh


=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

=> Building Routes...
=> [✓] Routes Built: 3.867ms
=> Copying public directory...
=> [✓] Public directory copied: 5.047ms
=> Bundling App...
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
=> [✓] App Bundled: 77405.436ms
=> Fetching Site Data...
=> [✓] Site Data Downloaded: 0.081ms
=> Fetching Route Data...
=> [==] 2/2 100% 667/s 0.0s 
=> [✓] Route Data Downloaded: 3.384ms
=> Exporting Route Data...
=> [✓] Route Data Exported: 0.275ms

  TypeError: (0 , _reactStatic.getSiteProps) is not a function
  
  - static.99ab2e6a.js:3982 Object.<anonymous>
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:3982:14
  
  - static.99ab2e6a.js:30 __webpack_require__
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:30:30
  
  - static.99ab2e6a.js:3840 Object.<anonymous>
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:3840:12
  
  - static.99ab2e6a.js:30 __webpack_require__
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:30:30
  
  - static.99ab2e6a.js:73 
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:73:18
  
  - static.99ab2e6a.js:11 
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:11:17
  
  - static.99ab2e6a.js:3 webpackUniversalModuleDefinition
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:3:20
  
  - static.99ab2e6a.js:1 Object.<anonymous>
    /home/decades/dfja/dragonfly2/spa/dist/static.99ab2e6a.js:1:1
  
  - loader.js:778 Module._compile
    internal/modules/cjs/loader.js:778:30
  
  - node.js:144 loader
    [spa]/[babel-register]/lib/node.js:144:5
  

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dragonfly-java-dashboard@1.8.0 build: `react-static build && sh ./cp.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dragonfly-java-dashboard@1.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/decades/.npm/_logs/2020-11-26T15_52_46_297Z-debug.log
decades@ubuntu:~/dfja/dragonfly2/spa$ 
```

What can I do with this?

**Comment by SleeplessByte** [comment]
Did you perhaps delete `yarn.lock` or `package-lock.json` when / have that not committed? What could have happened when you migrated to the new machine is that it didn't have these lock files and therefore updated some dependencies to _newer_ versions, breaking your build.

**Comment by neilyoung** [comment]
No. Nothing of that. After hours of deinstall/install on ubuntu it works now. Don't ask me why...

**Comment by SleeplessByte** [comment]
Ugh. I feel for you. But happy you go there! 💖

**Comment by neilyoung** [comment]
Thanks :)
