### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by ComputerCarl** [nozzle/react-static#294]
While using the app in development mode, everything seems to run as expected.

When attempting to build, I get a ` Cannot read property 'length' of undefined` error.
Normally, when this happens, I go around and add some `whatEver.someThing && whatEver.someThing.length` but I cannot track this error down. I have not been building as I've gone along.. just using the dev build.

````js
$ yarn build
yarn run v1.3.2
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 18.463ms
=> Building Routes...
=> [✓] Routes Built: 7.917ms
=> Bundling App...
=> [✓] App Bundled: 40003.599ms
=> Exporting Routes...
TypeError: Cannot read property 'length' of undefined
    at bitwise (I:\Projects\magazine\node_modules\shorthash\shorthash.js:18:10)
    at Object.unique (I:\Projects\magazine\node_modules\shorthash\shorthash.js:66:26)
    at I:\Projects\magazine\node_modules\react-static\lib\static.js:189:57
    at Array.forEach (<anonymous>)
    at _callee$ (I:\Projects\magazine\node_modules\react-static\lib\static.js:178:59)
    at tryCatch (I:\Projects\magazine\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (I:\Projects\magazine\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (I:\Projects\magazine\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (I:\Projects\magazine\node_modules\react-static\lib\static.js:120:191)
    at I:\Projects\magazine\node_modules\react-static\lib\static.js:120:361
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by ComputerCarl** [comment]
My own stupid mistake. Sorry! This is a very awesome project and I loved Tanner's enthusiasm in the introductory video!

**Comment by erquhart** [comment]
For anyone else who ran into this and is like BUT HOW DID YOU FIX IT, try removing any undefined values being returned by any of your `getData` methods in `static.config.js`.

**Comment by tannerlinsley** [comment]
Also, be sure to upgrade to 5.1.12, where this issue is fixed!
