### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by brandonmbanks** [nozzle/react-static#299]
Hi there! I'm excited to start using react-static. Unfortunately, when I run `npm start` I get an error.
```
→ npm start

> react-static-example-basic@1.0.1 start /path-to-directory
> react-static start

/path-to-directory/static.config.js:3
export default {};
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at loader (/path-to-directory/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path-to-directory/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-static-example-basic@1.0.1 start: `react-static start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-static-example-basic@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/banks/.npm/_logs/2018-01-15T16_28_46_715Z-debug.log
```

Node Version: v9.3.0
NPM version: 5.6.0

Please let me know if you need anything else from me. Thank you!

**Comment by tannerlinsley** [comment]
1. Make sure your global `react-static` package is up to date.
2. Use a yarn or npm script when possible eg. `yarn start` => `react-static start` in your package.json scripts.
3. Make sure you have a `.babelrc` file in your project. Please reference this file: https://github.com/nozzle/react-static/blob/master/examples/basic/.babelrc

**Comment by tannerlinsley** [comment]
Reopen if you are still encountering this issue. 🤘
