### ISSUE TITLE
where to include google analytics code

### ISSUE THREAD

**Issue by gmchaturvedi1** [nozzle/react-static#44]
Dear Friends,

when i am adding analytic code in <Head> Tag showing following error:
/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/static.config.js: Unexpected token, expected } (80:59)
  78 |             <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>
  79 |             <script>
> 80 |       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     |                                                            ^
  81 |       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  82 |       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  83 |       })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    at Parser.pp$5.raise (/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$9.jsxParseExpressionContainer (/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_modules/babylon/lib/index.js:7121:8)
    at Parser.pp$9.jsxParseElementAt (/home/gmchaturvedi/Documents/ProductionApps/go4edu/go4edu/node_m

**Comment by tannerlinsley** [comment]
You will want to use reacts dangerously set inner HTML attribute and manually set the contents of a script tag to a string containing your analytics code.

**Comment by gmchaturvedi1** [comment]
Thanks
