### ISSUE TITLE
Issues with woff2 font files

### ISSUE THREAD

**Issue by i8ramin** [nozzle/react-static#456]
Hi. Not entirely sure whats causing this, and it seems to only happen during the build stage. But it looks like something is trying to load the woff files in an associated module during the build process. The module that is included in my project has some web fonts along side the other React components, within the same source directory.

```
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 1.602ms
=> Building Routes...
=> [✓] Routes Built: 271.802ms
=> Bundling App...
=> [✓] App Bundled: 6799.957ms
=> Exporting Routes...
/node_modules/@private/custom-components/fonts/apercu/apercu_light.woff2:1
(function (exports, require, module, __filename, __dirname) { wOF2


SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (./node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/@private/custom-components/styles/fonts.js:17:22)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (./node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Digging into the stacktrace a bit, it looks like the line it is choking on is:

`var _apercu_light5 = require('../fonts/apercu/apercu_light.woff2');`

Which comes after a few other requires:

```
var _styledComponents = require('styled-components');
var _apercu_light = require('../fonts/apercu/apercu_light.eot');
var _apercu_light2 = _interopRequireDefault(_apercu_light);
var _apercu_light3 = require('../fonts/apercu/apercu_light.woff');
var _apercu_light4 = _interopRequireDefault(_apercu_light3);
var _apercu_light5 = require('../fonts/apercu/apercu_light.woff2');
```

Which makes me think that it is related to the specific `woff2` filetype.

**Comment by i8ramin** [comment]
*Update:* I found a clue: https://github.com/nozzle/react-static/blob/master/src/utils/binHelper.js

Looks like `woff2` isn't one of the ignored extensions. I think this may be the problem. Going to do some local testing and report back

**Comment by tannerlinsley** [comment]
Oh awesome! Yeah I was just about to paste a link to that file. PR when you can! 👍👏
