### ISSUE TITLE
How to include babel-polyfill

### ISSUE THREAD

**Issue by mbbender** [nozzle/react-static#471]
I'm trying to use redux-box project and created a new basic react-static project. Redux-box indicates including babel-polyfill if getting errors and I'm getting a regenerate runtime error which seems to be related to needing babel-polyfill. I don't understand all the parts, but it seems you can include babel-polyfill in weback so I modified static.config.js as follows:

```
import 'babel-polyfill'
export default {
    ...
    webpack: previousConfig => {
        const newConfig = Object.assign({}, previousConfig)
        newConfig.entry = ['babel-polyfill', previousConfig.entry]
        return newConfig
    },
}
```

However, I'm not sure if it's related but I get this error when running `yarn build` now

```
=> Exporting HTML...
{ Invariant Violation: React.Children.only expected to receive a single React element child.
    at invariant (/Users/michael/Code/sandbox/redux-box/node_modules/fbjs/lib/invariant.js:42:15)
    at Object.onlyChild [as only] (/Users/michael/Code/sandbox/redux-box/node_modules/react/cjs/react.development.js:975:31)
    at Provider.render (/Users/michael/Code/sandbox/redux-box/node_modules/react-redux/lib/components/Provider.js:63:30)
    at resolve (/Users/michael/Code/sandbox/redux-box/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/michael/Code/sandbox/redux-box/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/michael/Code/sandbox/redux-box/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/Users/michael/Code/sandbox/redux-box/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at renderToStringAndExtract (/Users/michael/Code/sandbox/redux-box/node_modules/react-static/lib/static/index.js:524:68)
    at Object.renderToHtml (/Users/michael/Code/sandbox/redux-box/node_modules/react-static/lib/static/getConfig.js:151:14)
    at _callee5$ (/Users/michael/Code/sandbox/redux-box/node_modules/react-static/lib/static/index.js:562:39) name: 'Invariant Violation', framesToPop:1 }
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c react-static build
Directory: /Users/michael/Code/sandbox/redux-box
Output:
".
```

**Comment by tannerlinsley** [comment]
Are you using `preact`?

**Comment by tannerlinsley** [comment]
Also, make sure that `<Router>` only has one children.

**Comment by mbbender** [comment]
Oh yeah I guess I did select `preact`. I didn't mean to introduce that variable already though. You think that's the issue?

**Comment by tannerlinsley** [comment]
Could be a bug with the preact option.

**Comment by tannerlinsley** [comment]
Looks like its a minor problem with the preact option. This will be fixed in the next release.
