### ISSUE TITLE
react-static-routes.js: Octal literal in strict mode

### ISSUE THREAD

**Issue by AlexandreChevalier** [nozzle/react-static#49]
Paths in `react-static-routes.js` still contain `\` on Windows when running `react-static start` and `react-static build` commands. It works fine when running `npm run start`.

Example : 
`import src_containers____ from 'C:\Users\Alexandre\site\src\containers\404`

**Comment by tannerlinsley** [comment]
Line https://github.com/nozzle/react-static/blob/master/src/static.js#L280 should be building a relative import using the route.component string you define in your static.config.js.

Are you on the latest version?

**Comment by AlexandreChevalier** [comment]
Yes version is 1.3.3
I just created a new project and tested the react-static start command right away and it writes absolute paths :

```
PS C:\Users\Alexandre\React\test> npm show react-static version
1.3.3

PS C:\Users\Alexandre\React\test> react-static start                                                                                                                   s:152:7)
=> Copying public directory...
=> [✓] Public directory copied: 2.766ms
=> Building Routes...
=> [✓] Routes Built: 1329.526ms
=> Building...
=> [✓] App serving at http://localhost:3000
Failed to rebuild.
./dist/react-static-routes.js
Syntax error: C:/Users/Alexandre/React/test/dist/react-static-routes.js: Octal literal in strict mode (9:77)

   7 | import src_containers_Post from 'C:\Users\Alexandre\React\test\src\containers\Post'
   8 | import src_containers_Blog from 'C:\Users\Alexandre\React\test\src\containers\Blog'
>  9 | import src_containers____ from 'C:\Users\Alexandre\React\test\src\containers\404'
     |                                                                              ^
  10 |
  11 |     export default class Routes extends Component {
  12 |       render () {
```

Do react-static start and build handle paths differently ?

**Comment by tannerlinsley** [comment]
No it doesn't.

**Comment by tannerlinsley** [comment]
Can you zip up your project and email it to me?

**Comment by tannerlinsley** [comment]
Just checked out your zip, everything is working fine for me after this:
`rm -r node_modules`
`yarn`
`yarn start`
and
`yarn build`
`yarn serve`

**Comment by AlexandreChevalier** [comment]
I just did that (rm and yarn) and now :
- `yarn start` and `yarn build` do not work (absolute paths with \ in them in react-static-routes.js)
- `react-static start` works well
- `react-static build` still does not work (absolute paths with \ in them in react-static-routes.js)

Stacktrace for react-static build :

```
=> Exporting Routes...
{ Error: Cannot find module 'react-static-routes'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/Alexandre/React/test/src/App.js:4:1)
    at Module._compile (module.js:624:30)
    at loader (C:\Users\Alexandre\AppData\Roaming\npm\node_modules\react-static\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Alexandre\AppData\Roaming\npm\node_modules\react-static\node_modules\babel-register\lib\node.j
s:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by AlexandreChevalier** [comment]
I tried the build netlify and now this error appears :

```
ERROR in app.js from UglifyJs
Unexpected token: name (AVAILABLE_LANGUAGES) [app.js:18815,8]
10:52:28 PM: 
=> There were ERRORS during the production build stage! :(
=> Fix them and try again!
=> [✓] App Bundled: 6513.147ms
=> Exporting Routes...
10:52:29 PM: /opt/build/repo/node_modules/api-ai-javascript/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from "./es6/ApiAiClient";
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

**Comment by tannerlinsley** [comment]
Can you point us to a repo with the code so we can take another look?

**Comment by AlexandreChevalier** [comment]
My last problem came from the api-ai-javascript package incompatibility with UglifyJs so I removed it and it's ok now. Since it builds well on netlify, it's fine for me.
Thanks for your help.
