### ISSUE TITLE
 Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by oliviaoddo** [nozzle/react-static#507]
I know this issue has come up a few times, and I read through the other ones, but I wasn't able to find a solution. 

I am using [this package ](https://www.npmjs.com/package/react-typeform-embed) and the import (`import { ReactTypeformEmbed } from 'react-typeform-embed';`)  is breaking the react-static build.
When I remove the import and remove the `ReactTypeformEmbed` component  everything builds fine. Any suggestions are greatly appreciated!

```
import React from 'react';
import PropTypes from 'prop-types';
import { ReactTypeformEmbed } from 'react-typeform-embed';

class Popup extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      open: false,
    };
  }

  render() {
    return (
      <div onClick={this.openForm}>
        <ReactTypeformEmbed
          popup
          autoOpen={false}
          url={'https://typeform/47tfskfnskjd'}
          hideHeaders
          hideFooter
          style={{ top: 100 }}
          ref={tf => this.typeformEmbed = tf}
        />
        {this.props.children}
      </div>
    );
  }
  openForm = () => {
    this.setState({ open: !this.state.open });
    this.typeformEmbed.typeform.open();
  };
}

Popup.propTypes = {
  children: PropTypes.shape(Array),
};

export default Popup;
```

Error

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at a.renderDOM (/usr/local/lib/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:391)
    at a.render (/usr/local/lib/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:228)
    at a.read (/usr/local/lib/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:250)
    at renderToString (/usr/local/lib/node_modules/react-static/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:6)
    at renderToStringAndExtract (/usr/local/lib/node_modules/react-static/lib/static.js:375:68)
    at Object.renderToHtml (/Users/oliviaoddo/Sites/Enki/native/landing-page/Enki.com/static.config.js:39:18)
    at _callee3$ (/usr/local/lib/node_modules/react-static/lib/static.js:408:39)
    at tryCatch (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:114:21)
```

**Comment by JustFly1984** [comment]
Looks like the component does not optimized for serverside rendering. Very possible that it uses unsafe call to window or document.

**Comment by oliviaoddo** [comment]
oh interesting, I had a feeling it had to do with the package @JustFly1984

**Comment by tannerlinsley** [comment]
You can wrap the component in a `typeof document !== undefined` check and import it with `require` to get around that. Just use a dummy component that renders `null` as the fallback.

**Comment by tannerlinsley** [comment]
Reopen if needed or if the issue progresses :)

**Comment by oliviaoddo** [comment]
Info on wrapping the component in a typeof document !== undefined check:

https://github.com/nozzle/react-static/blob/master/docs/concepts.md#writing-universal-node-safe-code
