### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled Promise Rejection in axios in react-static@>5.6.8

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#542]
I've been updating `react-static` from 5.6.8 to 5.7.1 and get an Error: Unhandled promise rejection. 
<img width="691" alt="screenshot 2018-04-05 12 40 26" src="https://user-images.githubusercontent.com/2255993/38347912-f52c9596-38d0-11e8-8f10-a5a58effd66d.png">

This issue does not exists in 5.6.8.

Additional information:
I'm embedding `aws-amplify` authentication into my new `react-static` app, and it has has it's own axios dependency, which has newer version 17.1 (react-static depends on 16.2), so this colored short errors comes from newer version of axios.

I want to point out, that I'm not calling `axios` in `static.config.js` nor elsewhere in my codebase.

If I'm getting rid of `aws-amplify`, I get long Error stack: 
```
> NODE_ENV=development PUBLIC_URL=https://localhost:3000 react-static start


UnhandledPromiseRejectionWarning: Unhandled Promise Rejection
{ Error: Request failed with status code 404
    at createError (/Users/justfly/projects/aggrow-static/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/justfly/projects/aggrow-static/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/justfly/projects/aggrow-static/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.16.2' },
     method: 'get',
     url: '/__react-static__/getMessagePort',
     data: undefined },
  request:
   ClientRequest {
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 154,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 21,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 407 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 154,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 21,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 407 },
     _header: 'GET /__react-static__/getMessagePort HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nHost: localhost\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/__react-static__/getMessagePort',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [Socket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http:/__react-static__/getMessagePort',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http:/__react-static__/getMessagePort' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { date: 'Thu, 05 Apr 2018 05:03:05 GMT',
        server: 'Apache/2.4.28 (Unix)',
        'content-length': '229',
        connection: 'close',
        'content-type': 'text/html; charset=iso-8859-1' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: '/__react-static__/getMessagePort',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'GET /__react-static__/getMessagePort HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nHost: localhost\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/__react-static__/getMessagePort',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /__react-static__/getMessagePort was not found on this server.</p>\n</body></html>\n' } }
=> Building Routes...
=> [✓] Routes Built: 3.084ms
=> Building App Bundle...
```

**Comment by tannerlinsley** [comment]
I'll look into this

**Comment by tannerlinsley** [comment]
Do you have any custom webpack dev server settings?

**Comment by JustFly1984** [comment]
Tanner, with last version this bug fixed. I do have custom webpack config to support CSS modules.

**Comment by tannerlinsley** [comment]
I still can't figure out what is causing this. Is this reproducible on a fresh install (or anything close) of any templates?

**Comment by JustFly1984** [comment]
I still have same issue on 2 of my projects

2018-05-24 1:13 GMT+08:00 stale[bot] <notifications@github.com>:
