### ISSUE TITLE
Code splitting ?

### ISSUE THREAD

**Issue by crubier** [nozzle/react-static#66]
Is there any way to make react-static work with webpack dynamic imports ?

https://webpack.js.org/guides/code-splitting/

When trying to build the app, I get the following result:

```
=> [✓] App Bundled: 25492.696ms
=> Exporting Routes...
/Users/crubier/Code/xxx/index.js:52
                return import( /* webpackChunkName: "lodash" */"lodash");
                       ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at loader (/Users/crubier/Code/xxx/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/crubier/Code/xxx/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/crubier/Code/xxx/src/containers/World.js:2:1)
    at Module._compile (module.js:624:30)
    at loader (/Users/crubier/Code/xxx/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js]
 (/Users/crubier/Code/xxx/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)

```

**Comment by crubier** [comment]
The code works well in dev-server ( `npm start` ) because the dynamic import are supported by webpack and transpiled. However, static generation is performed with node, without using transpiled code, and node chokes on the `import()` syntax...

A possible solution would be to use `app.js` to perform server side rendering, instead of using source files directly.

**Comment by tannerlinsley** [comment]
This will be solved this weekend hopefully.

**Comment by crubier** [comment]
At the same time, it would be nice if the name `app.js` was not hardcoded into react static, this would allow to follow the guidelines of webpack concerning caching.  https://webpack.js.org/guides/caching/

```
output: {
        filename: "[name].[chunkhash].js",
}
```

**Comment by tannerlinsley** [comment]
Agreed. I'll fix this.

**Comment by tannerlinsley** [comment]
One challenge with implementing the caching fixes is that we are currently unable to use the HtmlWebpackPlugin. Any ideas on that front would be a huge help.

**Comment by crubier** [comment]
Why are we unable to use HtmlWebpackPlugin ? I thought it was used to generate the (static) HTML

**Comment by tannerlinsley** [comment]
No that's normally used to generate the index.htm file and populate it with
all of the dynamically generated link tags and bundle script references

**Comment by tannerlinsley** [comment]
@crubier I'd love it if you could join the slack org here: https://react-chat-signup.herokuapp.com/ and join the #react-static channel to discuss more of this.  I would also like to get code-splitting working for you, but I'll need an example of what you want to do.

**Comment by tannerlinsley** [comment]
I would be curious if this works in the latest major version. Quite a few changes have been made to make things like this possible. One thing that you want to do is make a component that would **only** asynchronously import in production, that way the dev and node versions can operate synchronously and export as normal.

**Comment by tannerlinsley** [comment]
I'm interested in this enhancement, but going to close this for now. Happy to keep working on it though.

**Comment by crubier** [comment]
For your info, It works out of the box in 3.0.5 ! yay! 

Here is the code of the "about" page with an additional async component:

```javascript
// src/containers/About.js
export default class About extends React.Component {
  constructor(...args) {
    super(...args)
    this.state = { MyComponent: null }
  }
  async componentWillMount() {
    await new Promise(resolve => setInterval(resolve, 1000))
    const { MyComponent } = await import('../components/MyComponent')

    this.setState({ MyComponent, tries: this.state.tries + 1 })
  }
  render() {
    const { MyComponent } = this.state
    if (MyComponent !== null) {
      return (
        <div>
          <h1>This is what we're all about.</h1>
          <MyComponent />
          <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
        </div>
      )
    }
    return (
      <div>
        <h1>This is what we're all about.</h1>
        <div>
          <h1>Loading this heavy component...</h1>
        </div>
        <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
      </div>
    )
  }
}
```


```javascript
//src/components/MyComponent.js
import React from 'react'
//

export const MyComponent = () => (
  <div>
    <h1>The heavy component has loaded !</h1>
  </div>
)

```

**Comment by crubier** [comment]
Feel free to add this as an additional example. Please note however that the component is generated in its "unloaded" state in the static pages.

To generate it in its loaded state would need some more specific code.

**Comment by tannerlinsley** [comment]
Does this work for static builds?

**Comment by crubier** [comment]
Nice ! I will try that, what is your recommended method to check for the non browser environment ?

**Comment by tannerlinsley** [comment]
Though your users might end up seeing a flash of content change in first load when react mounts on top of the full HTML, renders , and then waits to load the async component

**Comment by tannerlinsley** [comment]
If (typeof document === "undefined") {
  Do static build Stuff
}

**Comment by crubier** [comment]
So to recap my findings:

# Option 1: render loaded state in static build

It is indeed possible to render to the loaded state in static build with the following code:

```jsx
// src/containers/About.js
import React from 'react'

const Failed = () => (
  <div style={{ color: 'red' }}>
    <h1>Failed to load the heavy component!</h1>
  </div>
)

const Loading = () => (
  <div style={{ color: 'yellow' }}>
    <h1>Loading this heavy component...</h1>
  </div>
)

export default class About extends React.Component {
  constructor(...args) {
    super(...args)
    this.state = { MyComponent: null }
  }
  componentWillMount() {
    if (typeof document === 'undefined') {
      const { MyComponent } = require('../components/MyComponent')
      this.setState({ MyComponent })
    } else {
      import('../components/MyComponent')
        .then(({ MyComponent }) => this.setState({ MyComponent }))
        .catch(error => this.setState({ MyComponent: Failed }))
    }
  }
  render() {
    const { MyComponent } = this.state
    if (MyComponent !== null) {
      return (
        <div>
          <h1>This is what we're all about.</h1>
          <MyComponent />
          <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
        </div>
      )
    }
    return (
      <div>
        <h1>This is what we're all about.</h1>
        <Loading />
        <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
      </div>
    )
  }
}
```

```jsx
//src/components/MyComponent.js
import React from 'react'

export const MyComponent = () => (
  <div style={{ color: 'green' }}>
    <h1>Heavy component loaded !</h1>
  </div>
)
```

However, as expected, I get this warning when rehydrating:

```
Warning: Text content did not match. Server: "Heavy component loaded !" Client: "Loading this heavy component..."
```

The lifecycle of the component looks like this: 

  1. loaded state in static render
  2. non-loaded state when react mounts (rehydrate)
  3. loaded state again once the dynamic import is resolved

# Option 2: render non loaded state in static build


```jsx
// src/containers/About.js
import React from 'react'

const Failed = () => (
  <div style={{ color: 'red' }}>
    <h1>Failed to load the heavy component!</h1>
  </div>
)

const Loading = () => (
  <div style={{ color: 'yellow' }}>
    <h1>Loading this heavy component...</h1>
  </div>
)

export default class About extends React.Component {
  constructor(...args) {
    super(...args)
    this.state = { MyComponent: null }
  }
  componentWillMount() {
    import('../components/MyComponent')
      .then(({ MyComponent }) => this.setState({ MyComponent }))
      .catch(error => this.setState({ MyComponent: Failed }))
  }
  render() {
    const { MyComponent } = this.state
    if (MyComponent !== null) {
      return (
        <div>
          <h1>This is what we're all about.</h1>
          <MyComponent />
          <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
        </div>
      )
    }
    return (
      <div>
        <h1>This is what we're all about.</h1>
        <Loading />
        <p>React, static sites, performance, speed. It's the stuff that makes us tick.</p>
      </div>
    )
  }
}
```

```jsx
//src/components/MyComponent.js
import React from 'react'

export const MyComponent = () => (
  <div style={{ color: 'green' }}>
    <h1>Heavy component loaded !</h1>
  </div>
)
```

To be honest this behaviour was very good for my use case anyway, and is more logical (no flash of unloaded state)

  1. non-loaded state in static render
  2. non-loaded state when react mounts (rehydrate)
  3. loaded state again once the dynamic import is resolved

**Comment by crubier** [comment]
I think the second option is definitely worth adding to the examples. It just feels right and it works as expected out of the box.

**Comment by crubier** [comment]
See PR #98

**Comment by cthurston** [comment]
I'm trying to use lodash-es in the static.config.js.  

````
import groupBy from 'lodash-es/groupBy'
````

I get this error:  

````
C:\public-static\node_modules\lodash-es\groupBy.js:1
(function (exports, require, module, __filename, __dirname) { import baseAssignValue from './_baseAssignValue.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\public-static\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
````

I can't tell from the examples if this is supported or not.
