### ISSUE TITLE
Cannot find module es6.object.to-string on windows 10

### ISSUE THREAD

**Issue by podabed** [nozzle/react-static#67]
Just used command "npm -g i react-static" and "react-static create myblog"

This is error:
`λ react-static create myblog
module.js:529
    throw err;
    ^

Error: Cannot find module '../../modules/es6.object.to-string'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\windows\AppData\Roaming\npm\node_modules\react-static\node_modules\core-js\library\fn\symbol\index.js:2:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)`

I've tried reinstallation and this is not help.

**Comment by tannerlinsley** [comment]
Don't put the name of your new project in the command.

**Comment by podabed** [comment]
This error even in existing project. It was work about a week ago.

**Comment by tannerlinsley** [comment]
Please update to the latest version in your existing project and try again. The library is still very young, so there are new releases almost every day or two.

**Comment by podabed** [comment]
Already. This error in new version.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please upgrade both global and local packages to version 2.0.0
