### ISSUE TITLE
 Error: Cannot find module 'babel-runtime/regenerator' since 6.0.0-beta.9

### ISSUE THREAD

**Issue by xlwknx** [nozzle/react-static#685]
➜  website git:(master) ✗ react-static start
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-static/lib/commands/start.js:8:43)
    at Module._compile (module.js:652:30)
    at Module._compile (/usr/local/lib/node_modules/react-static/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/react-static/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)

### Environment

1.  `react-static -v`: 6.0.0-beta.9
2.  `node -v`: v8.11.1
3.  `yarn --version or npm -v`: 1.7.0
4.  Operating system: MacOS

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  npm install -g react-static@6.0.0-beta.9 (latest also)
2.  react-static start
3.  profit!

**Comment by danilobuerger** [comment]
Duplicate #684 and #670. Fixed in master.

**Comment by KidkArolis** [comment]
I can confirm it's broken in react-static@6.0.0-beta.16

It should have been fixed in react-static@6.0.0-beta.15 or react-static@6.0.0-beta.16, but I think something went wrong with the npm release. cc @tannerlinsley 

If I use master - it works.

**Comment by danilobuerger** [comment]
Apparently `swimmer` is being pulled in which doesn't use babel 7 yet. It looks like it works with master (instead of the npm package) as the dev dependency still pull in the old `babel-runtime` via `jest`.

@tannerlinsley If you don't mind, I would PR the `swimmer` repo.

**Comment by KidkArolis** [comment]
I don't think this is fixed since there hasn't been any new releases since this issue was filed.
