### ISSUE TITLE
module.js:549 throw err;

### ISSUE THREAD

**Issue by pcabrera83** [nozzle/react-static#737]
When I run  react-static create I get the error message at the bottom. 

Environment
1.  node v 8.11.3
3.  npm v 6.4.1
4.  Operating system: MacOS High Sierra v.10.13.6

Steps to Reproduce the problem
1.  npm install -g react-static
2.  react-static create
3. 

```
module.js:549
    throw err;
    ^
Error: Cannot find module '../lib/utils/binHelper'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-static/bin/react-static-create:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by kouhot** [comment]
Seems like It's fixed in latest version `6.0.0-beta.20`.

**Comment by pcabrera83** [comment]
Which version? `react-static`?

**Comment by pcabrera83** [comment]
I'm running `6.0.0-beta.17`

**Comment by tannerlinsley** [comment]
@latest will now resolve to the latest stable version.

**Comment by pcabrera83** [comment]
If you are newbie like muah and are wondering how to update your package. 

Try:

1. npm install -g react-static@next

2. react-static create name_project
