### ISSUE TITLE
[v6] 'react-static create' fails with 'TypeError: The "path" argument must be of type string'

### ISSUE THREAD

**Issue by alex996** [nozzle/react-static#862]
**Description**

When I try to create a project with `react-static` **v6**, I get an error `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string`.

**Reproduction**
1. `npm i -g react-static@next` (or `@6.0.0-beta.30`)
2. `react-static create`
3. Press `Enter` for each option
4. Observe the error

```sh
? What should we name this project? my-static-site
? Select a template below... basic
=> Creating new react-static project...

Downloading NPM template: react-static-example-basic@6.0.0-beta.30
{ Error: Command failed: yarn pack react-static-example-basic@6.0.0-beta.30
error Couldn't find a package.json file in "/home/alex/Workspace/projects"

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn pack react-static-example-basic@6.0.0-beta.30' }
Downloading NPM template: react-static-example-basic@6.0.0-beta.30 failed!
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.
  Received type undefined
  
  - path.js:39 assertPath
    path.js:39:11
  
  - path.js:1085 Object.resolve
    path.js:1085:7
  
  - create.js:391 Object._callee2$
    [lib]/[react-static]/lib/commands/create.js:391:58
  
  - runtime.js:62 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as throw]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:114:21
  
  - create.js:56 asyncGeneratorStep
    [lib]/[react-static]/lib/commands/create.js:56:103
  
  - create.js:58 _throw
    [lib]/[react-static]/lib/commands/create.js:58:291
  
  - next_tick.js:77 process.internalTickCallback
```

Note that
- I get the same error with `yarn global add react-static@next`
- I tried latest node `11.2.0` and `10.13.0`, same exact issue

The top-most error is `Couldn't find a package.json file` in current directory, so if I do `npm init -y`, and then `react-static-create`, I get a different error

```sh
? What should we name this project? my-static-site
? Select a template below... markdown
=> Creating new react-static project...

Downloading NPM template: react-static-example-markdown@6.0.0-beta.30
yarn pack v1.12.3
success Wrote tarball to "/home/alex/Workspace/projects/my-static-site/my-static-site-v1.0.0.tgz".
Done in 0.04s.

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/alex/Workspace/projects/my-static-site/yarn pack v1.12.3success Wrote tarball to "/home/alex/Workspace/projects/my-static-site/my-static-site-v1.0.0.tgz".Done in 0.04s.'
Emitted 'error' event at:
    at /home/alex/.nvm/versions/node/v11.2.0/lib/node_modules/react-static/node_modules/graceful-fs/graceful-fs.js:207:14
    at /home/alex/.nvm/versions/node/v11.2.0/lib/node_modules/react-static/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.oncomplete (fs.js:148:20)
```

P.S. `v5` works like charm! I'd prefer to jump on the babel 7 / webpack 4 wagon though. Thanks!

**Expected behavior**

It should bootstrap a project with v6.

**Actual behavior**

It fails with a cryptic error.

**Environment**

OS / terminal: Ubuntu 18.10 cosmic (linux x64) / Bash
`node -v`: `11.2.0`
`npm -v`: `6.4.1`
`yarn -v`: `1.12.3`

**Comment by tannerlinsley** [comment]
This is fixed in the latest beta! Yay!
