### ISSUE TITLE
react-static start Fails for Styled Components Example

### ISSUE THREAD

**Issue by JoshRosenstein** [nozzle/react-static#91]
React-Static 3.0.4

Tested:
React-static create >Styled-Components>Yarn Start **Fails** (Log Below)
React-static create >Styled-Components>Yarn Build **Works**
React-static create >basic>Yarn Start **Works**

Response:
$ yarn start
yarn run v1.2.1
$ react-static start
TypeError: Cannot read property 'styleTags' of undefined
    at CustomHtml.render (E:/Programming/react/react-static-test/static.config.js:57:14)
    at resolve (E:\Programming\react\react-static-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:2646:18)
    at ReactDOMServerRenderer.render (E:\Programming\react\react-static-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:2746:22)
    at ReactDOMServerRenderer.read (E:\Programming\react\react-static-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:2722:19)
    at renderToStaticMarkup (E:\Programming\react\react-static-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:2991:25)
    at _callee$ (E:\Programming\react\react-static-test\node_modules\react-static\lib\commands\start.js:84:53)
    at tryCatch (E:\Programming\react\react-static-test\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\Programming\react\react-static-test\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (E:\Programming\react\react-static-test\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (E:\Programming\react\react-static-test\node_modules\react-static\lib\commands\start.js:43:191)
error Command failed with exit code 1.

**Comment by depadiernos** [comment]
I get the same error when using npm.

**Comment by tannerlinsley** [comment]
Fixed in 19dd730101984e5af4e21bdaf066e71f2ba1a745, upgrade to latest :)
