### ISSUE TITLE
New version breaks commands

### ISSUE THREAD

**Issue by TomerAberbach** [nozzle/react-static#939]
### Are you reporting a bug?

Yes, commit 7ae29f3172359b02992fbf1df632bd5dc9baf54e breaks the `react-static start` command and probably all other commands if I had to guess. I get the following error output:

```
$ react-static start
/home/tomeraberbach/Desktop/spotify-application/node_modules/react-static/bin/react-static:128
  ${/*-i, --incremental     Performan an incremental/partial export*/}
                                                                     ^

SyntaxError: Unexpected token }
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

I took a look at the commit I mentioned and it looks like a bunch of `${/* some comment */}` were added in template strings. I think the JavaScript parser expects an actual value in the interpolated part of the string which is why the error occurs.

### Environment

1.  `react-static -V`: Also errors with the same output.
2.  `node -v`: v10.14.1
3.  `npm -v`: 6.5.0
4.  Operating system: Ubuntu 18.10

### Steps to Reproduce the problem

Run any `react-static` command.

**Comment by tannerlinsley** [comment]
Good catch. Surprised my linter/tests didn't bark at this. Fixed in latest patch!

**Comment by TomerAberbach** [comment]
I just updated on my end and it looks like it works fine now.
